-- ============================================================================
-- FACILITATOR APPROVAL SYSTEM
-- ============================================================================
-- This creates a controlled access system for facilitators
-- Only approved people can create workshops/events/retreats
-- ============================================================================

-- ============================================================================
-- STEP 1: Create Facilitator Requests Table
-- ============================================================================
-- Stores requests from people who want to become facilitators

CREATE TABLE IF NOT EXISTS public.facilitator_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  -- Applicant Information
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone_number text NOT NULL,
  message text, -- Why they want to be a facilitator

  -- Request Status
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'rejected')),

  -- Review Information
  reviewed_at timestamp with time zone,
  reviewed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  admin_notes text -- Internal notes from admin
);

-- ============================================================================
-- STEP 2: Create Approved Facilitators Table
-- ============================================================================
-- Stores approved facilitators (whitelist for registration)

CREATE TABLE IF NOT EXISTS public.approved_facilitators (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  -- Facilitator Information (from approved request)
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  phone_number text NOT NULL,

  -- Link to Auth User (null until they register)
  user_id uuid UNIQUE REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Approval Information
  approved_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,

  -- Status
  is_active boolean DEFAULT true NOT NULL
);

-- ============================================================================
-- STEP 3: Create Indexes
-- ============================================================================

CREATE INDEX IF NOT EXISTS facilitator_requests_email_idx ON public.facilitator_requests(email);
CREATE INDEX IF NOT EXISTS facilitator_requests_status_idx ON public.facilitator_requests(status);
CREATE INDEX IF NOT EXISTS facilitator_requests_created_at_idx ON public.facilitator_requests(created_at DESC);

CREATE INDEX IF NOT EXISTS approved_facilitators_email_idx ON public.approved_facilitators(email);
CREATE INDEX IF NOT EXISTS approved_facilitators_user_id_idx ON public.approved_facilitators(user_id);
CREATE INDEX IF NOT EXISTS approved_facilitators_is_active_idx ON public.approved_facilitators(is_active);

-- ============================================================================
-- STEP 4: Enable Row Level Security
-- ============================================================================

ALTER TABLE public.facilitator_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approved_facilitators ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STEP 5: RLS Policies for Facilitator Requests
-- ============================================================================

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Anyone can create facilitator requests" ON public.facilitator_requests;
DROP POLICY IF EXISTS "Users can view their own requests" ON public.facilitator_requests;
DROP POLICY IF EXISTS "Admins can view all requests" ON public.facilitator_requests;
DROP POLICY IF EXISTS "Admins can update requests" ON public.facilitator_requests;
DROP POLICY IF EXISTS "Admins can delete requests" ON public.facilitator_requests;

-- 1. Anyone can submit a facilitator request (public form)
CREATE POLICY "Anyone can create facilitator requests"
  ON public.facilitator_requests FOR INSERT
  WITH CHECK (true);

-- 2. Users can view their own requests by email
CREATE POLICY "Users can view their own requests"
  ON public.facilitator_requests FOR SELECT
  USING (
    email = (SELECT email FROM auth.users WHERE id = auth.uid())
  );

-- 3. Authenticated users can view all requests (admins use this)
-- NOTE: In production, you'd want to restrict this to admin role only
CREATE POLICY "Authenticated users can view all requests"
  ON public.facilitator_requests FOR SELECT
  USING (auth.role() = 'authenticated');

-- 4. Authenticated users can update requests (approve/reject)
CREATE POLICY "Authenticated users can update requests"
  ON public.facilitator_requests FOR UPDATE
  USING (auth.role() = 'authenticated');

-- 5. Authenticated users can delete requests
CREATE POLICY "Authenticated users can delete requests"
  ON public.facilitator_requests FOR DELETE
  USING (auth.role() = 'authenticated');

-- ============================================================================
-- STEP 6: RLS Policies for Approved Facilitators
-- ============================================================================

DROP POLICY IF EXISTS "Authenticated users can view approved facilitators" ON public.approved_facilitators;
DROP POLICY IF EXISTS "Authenticated users can create approved facilitators" ON public.approved_facilitators;
DROP POLICY IF EXISTS "Authenticated users can update approved facilitators" ON public.approved_facilitators;
DROP POLICY IF EXISTS "Authenticated users can delete approved facilitators" ON public.approved_facilitators;

-- 1. Anyone can read approved facilitators list (for registration check)
CREATE POLICY "Anyone can view approved facilitators"
  ON public.approved_facilitators FOR SELECT
  USING (true);

-- 2. Authenticated users can create approved facilitators (admin approval)
CREATE POLICY "Authenticated users can create approved facilitators"
  ON public.approved_facilitators FOR INSERT
  WITH CHECK (auth.role() = 'authenticated');

-- 3. Authenticated users can update approved facilitators
CREATE POLICY "Authenticated users can update approved facilitators"
  ON public.approved_facilitators FOR UPDATE
  USING (auth.role() = 'authenticated');

-- 4. Authenticated users can delete approved facilitators
CREATE POLICY "Authenticated users can delete approved facilitators"
  ON public.approved_facilitators FOR DELETE
  USING (auth.role() = 'authenticated');

-- ============================================================================
-- STEP 7: Grant API Access Permissions
-- ============================================================================

GRANT ALL ON public.facilitator_requests TO authenticated;
GRANT INSERT ON public.facilitator_requests TO anon;
GRANT SELECT ON public.facilitator_requests TO anon;

GRANT ALL ON public.approved_facilitators TO authenticated;
GRANT SELECT ON public.approved_facilitators TO anon;

GRANT USAGE, SELECT ON SEQUENCE facilitator_requests_id_seq TO authenticated, anon;
GRANT USAGE, SELECT ON SEQUENCE approved_facilitators_id_seq TO authenticated, anon;

-- ============================================================================
-- STEP 8: Create Helper Function - Approve Request
-- ============================================================================
-- This function approves a request and adds to approved facilitators

CREATE OR REPLACE FUNCTION approve_facilitator_request(request_id bigint)
RETURNS void AS $$
DECLARE
  req_record RECORD;
BEGIN
  -- Get the request details
  SELECT * INTO req_record FROM public.facilitator_requests WHERE id = request_id;

  -- Insert into approved_facilitators
  INSERT INTO public.approved_facilitators (email, full_name, phone_number, approved_by)
  VALUES (req_record.email, req_record.full_name, req_record.phone_number, auth.uid());

  -- Update request status
  UPDATE public.facilitator_requests
  SET status = 'approved',
      reviewed_at = now(),
      reviewed_by = auth.uid()
  WHERE id = request_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================================================
-- STEP 9: Create Helper Function - Check if Email is Approved
-- ============================================================================

CREATE OR REPLACE FUNCTION is_approved_facilitator(check_email text)
RETURNS boolean AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.approved_facilitators
    WHERE email = check_email AND is_active = true
  );
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- SETUP COMPLETE!
-- ============================================================================

-- What this script created:
-- ✓ facilitator_requests table (stores access requests)
-- ✓ approved_facilitators table (whitelist for registration)
-- ✓ Performance indexes
-- ✓ Row Level Security (RLS) enabled
-- ✓ Security policies (who can view/create/update/delete)
-- ✓ Helper functions for approval workflow

-- Next Steps:
-- 1. Update your React app with new pages:
--    - /request-facilitator-access (public form)
--    - /dashboard/facilitator-requests (admin review)
-- 2. Update /register to check approved_facilitators
-- 3. Test the complete workflow

-- How It Works:
-- 1. User fills form at /request-facilitator-access
-- 2. Creates row in facilitator_requests (status: pending)
-- 3. Admin reviews in dashboard, clicks "Approve"
-- 4. Calls approve_facilitator_request(id) function
-- 5. Adds email to approved_facilitators table
-- 6. User can now register at /register (checks if email approved)
