-- Create a table for profiles if you want to store extra user data
-- Note: Supabase handles auth.users automatically. This is for public profile info.
create table public.profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for workshops
create table public.workshops (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  date timestamp with time zone not null,
  duration_minutes integer,
  price numeric,
  instructor_id uuid references public.profiles(id) not null,
  image_url text
);

-- RLS for workshops
alter table public.workshops enable row level security;

create policy "Workshops are viewable by everyone."
  on workshops for select
  using ( true );

create policy "Instructors can create workshops."
  on workshops for insert
  with check ( auth.uid() = instructor_id );

create policy "Instructors can update their own workshops."
  on workshops for update
  using ( auth.uid() = instructor_id );

create policy "Instructors can delete their own workshops."
  on workshops for delete
  using ( auth.uid() = instructor_id );
