-- Migration: Workshops to Offerings + RSVP System
-- Created: 2025-12-02
-- Description: Converts workshops table to offerings table with type support,
--              adds RSVP functionality with approval system

-- ============================================================================
-- STEP 1: Rename workshops table to offerings
-- ============================================================================

ALTER TABLE public.workshops RENAME TO offerings;

-- ============================================================================
-- STEP 2: Add new columns to offerings table
-- ============================================================================

-- Add type column (workshop, event, retreat)
ALTER TABLE public.offerings
ADD COLUMN type text NOT NULL DEFAULT 'workshop'
CHECK (type IN ('workshop', 'event', 'retreat'));

-- Add max participants
ALTER TABLE public.offerings
ADD COLUMN max_participants integer DEFAULT NULL;

-- Add status column (draft, published, cancelled)
ALTER TABLE public.offerings
ADD COLUMN status text NOT NULL DEFAULT 'published'
CHECK (status IN ('draft', 'published', 'cancelled'));

-- Add location
ALTER TABLE public.offerings
ADD COLUMN location text;

-- Update created_at to have a default if it doesn't already
ALTER TABLE public.offerings
ALTER COLUMN created_at SET DEFAULT timezone('utc'::text, now());

-- ============================================================================
-- STEP 3: Create RSVPs table
-- ============================================================================

CREATE TABLE public.rsvps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  -- Foreign key to offerings
  offering_id bigint REFERENCES public.offerings(id) ON DELETE CASCADE NOT NULL,

  -- Guest information (required)
  user_name text NOT NULL,
  user_email text NOT NULL,
  user_phone text,
  message text,

  -- Optional: Link to authenticated user
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,

  -- RSVP status (pending, approved, declined)
  status text NOT NULL DEFAULT 'pending'
  CHECK (status IN ('pending', 'approved', 'declined'))
);

-- Add index for faster queries
CREATE INDEX rsvps_offering_id_idx ON public.rsvps(offering_id);
CREATE INDEX rsvps_status_idx ON public.rsvps(status);
CREATE INDEX rsvps_created_at_idx ON public.rsvps(created_at DESC);

-- ============================================================================
-- STEP 4: Update RLS policies for offerings table
-- ============================================================================

-- Drop old workshop policies
DROP POLICY IF EXISTS "Workshops are viewable by everyone." ON public.offerings;
DROP POLICY IF EXISTS "Instructors can create workshops." ON public.offerings;
DROP POLICY IF EXISTS "Instructors can update their own workshops." ON public.offerings;
DROP POLICY IF EXISTS "Instructors can delete their own workshops." ON public.offerings;

-- Create new offerings policies
CREATE POLICY "Published offerings are viewable by everyone."
  ON public.offerings FOR SELECT
  USING (status = 'published');

CREATE POLICY "Instructors can view all their offerings."
  ON public.offerings FOR SELECT
  USING (auth.uid() = instructor_id);

CREATE POLICY "Instructors can create offerings."
  ON public.offerings FOR INSERT
  WITH CHECK (auth.uid() = instructor_id);

CREATE POLICY "Instructors can update their own offerings."
  ON public.offerings FOR UPDATE
  USING (auth.uid() = instructor_id);

CREATE POLICY "Instructors can delete their own offerings."
  ON public.offerings FOR DELETE
  USING (auth.uid() = instructor_id);

-- ============================================================================
-- STEP 5: Create RLS policies for rsvps table
-- ============================================================================

-- Enable RLS on rsvps table
ALTER TABLE public.rsvps ENABLE ROW LEVEL SECURITY;

-- Anyone can create an RSVP (public can RSVP to offerings)
CREATE POLICY "Anyone can create RSVPs."
  ON public.rsvps FOR INSERT
  WITH CHECK (true);

-- Public can view their own RSVPs (by email or user_id)
CREATE POLICY "Users can view their own RSVPs."
  ON public.rsvps FOR SELECT
  USING (
    auth.uid() = user_id
    OR
    user_email = auth.jwt() ->> 'email'
  );

-- Instructors can view RSVPs for their offerings
CREATE POLICY "Instructors can view RSVPs for their offerings."
  ON public.rsvps FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.offerings
      WHERE offerings.id = rsvps.offering_id
      AND offerings.instructor_id = auth.uid()
    )
  );

-- Instructors can update RSVP status for their offerings
CREATE POLICY "Instructors can update RSVPs for their offerings."
  ON public.rsvps FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.offerings
      WHERE offerings.id = rsvps.offering_id
      AND offerings.instructor_id = auth.uid()
    )
  );

-- Instructors can delete RSVPs for their offerings
CREATE POLICY "Instructors can delete RSVPs for their offerings."
  ON public.rsvps FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.offerings
      WHERE offerings.id = rsvps.offering_id
      AND offerings.instructor_id = auth.uid()
    )
  );

-- ============================================================================
-- STEP 6: Create helpful views (optional, for analytics)
-- ============================================================================

-- View for upcoming offerings
CREATE OR REPLACE VIEW public.upcoming_offerings AS
SELECT
  o.*,
  p.full_name as instructor_name,
  (SELECT COUNT(*) FROM rsvps WHERE rsvps.offering_id = o.id AND rsvps.status = 'approved') as approved_rsvps_count
FROM public.offerings o
LEFT JOIN public.profiles p ON p.id = o.instructor_id
WHERE o.status = 'published'
  AND o.date > NOW()
ORDER BY o.date ASC;

-- View for offerings with RSVP counts
CREATE OR REPLACE VIEW public.offerings_with_rsvp_counts AS
SELECT
  o.*,
  COUNT(CASE WHEN r.status = 'pending' THEN 1 END) as pending_count,
  COUNT(CASE WHEN r.status = 'approved' THEN 1 END) as approved_count,
  COUNT(CASE WHEN r.status = 'declined' THEN 1 END) as declined_count,
  COUNT(r.id) as total_rsvps
FROM public.offerings o
LEFT JOIN public.rsvps r ON r.offering_id = o.id
GROUP BY o.id;

-- Grant select on views to authenticated users
GRANT SELECT ON public.upcoming_offerings TO authenticated;
GRANT SELECT ON public.offerings_with_rsvp_counts TO authenticated;

-- ============================================================================
-- MIGRATION COMPLETE
-- ============================================================================

-- Run this script in your Supabase SQL editor to:
-- 1. Rename workshops → offerings
-- 2. Add type, status, max_participants, location fields
-- 3. Create rsvps table
-- 4. Set up all RLS policies
-- 5. Create helpful views

-- Notes:
-- - Existing workshop data will remain (type will default to 'workshop')
-- - All existing RLS policies are recreated with new names
-- - RSVP system is fully functional with approval workflow
