-- ============================================================================
-- CONSCIOUS SANCTUARY - COMPLETE DATABASE SETUP
-- ============================================================================
-- Run this entire script in your Supabase SQL Editor
-- This will create all tables, indexes, and security policies needed
-- ============================================================================

-- ============================================================================
-- STEP 1: Create Offerings Table
-- (Stores workshops, events, and retreats)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.offerings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  -- Basic Information
  title text NOT NULL,
  description text,
  date timestamp with time zone NOT NULL,
  duration_minutes integer NOT NULL DEFAULT 60,
  price numeric DEFAULT 0,
  image_url text,
  location text,

  -- Offering Type (workshop, event, retreat)
  type text NOT NULL DEFAULT 'workshop'
    CHECK (type IN ('workshop', 'event', 'retreat')),

  -- Publishing Status (draft, published, cancelled)
  status text NOT NULL DEFAULT 'published'
    CHECK (status IN ('draft', 'published', 'cancelled')),

  -- Participant Limits
  max_participants integer DEFAULT NULL,

  -- Instructor Reference (links to auth.users)
  instructor_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL
);

-- ============================================================================
-- STEP 2: Create RSVPs Table
-- (Stores registrations for all offerings)
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.rsvps (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,

  -- Foreign Key to Offerings
  offering_id bigint REFERENCES public.offerings(id) ON DELETE CASCADE NOT NULL,

  -- Guest Information (Required)
  user_name text NOT NULL,
  user_email text NOT NULL,
  user_phone text,
  message text,

  -- Optional: Link to Authenticated User
  user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,

  -- RSVP Status (pending, approved, declined)
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'approved', 'declined'))
);

-- ============================================================================
-- STEP 3: Create Indexes for Performance
-- ============================================================================

-- Offerings Indexes
CREATE INDEX IF NOT EXISTS offerings_instructor_id_idx ON public.offerings(instructor_id);
CREATE INDEX IF NOT EXISTS offerings_date_idx ON public.offerings(date DESC);
CREATE INDEX IF NOT EXISTS offerings_type_idx ON public.offerings(type);
CREATE INDEX IF NOT EXISTS offerings_status_idx ON public.offerings(status);

-- RSVPs Indexes
CREATE INDEX IF NOT EXISTS rsvps_offering_id_idx ON public.rsvps(offering_id);
CREATE INDEX IF NOT EXISTS rsvps_status_idx ON public.rsvps(status);
CREATE INDEX IF NOT EXISTS rsvps_created_at_idx ON public.rsvps(created_at DESC);
CREATE INDEX IF NOT EXISTS rsvps_user_id_idx ON public.rsvps(user_id);

-- ============================================================================
-- STEP 4: Enable Row Level Security (RLS)
-- ============================================================================

ALTER TABLE public.offerings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rsvps ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STEP 5: Create RLS Policies for Offerings
-- ============================================================================

-- Drop existing policies if they exist (for clean re-run)
DROP POLICY IF EXISTS "Published offerings are viewable by everyone" ON public.offerings;
DROP POLICY IF EXISTS "Instructors can view all their offerings" ON public.offerings;
DROP POLICY IF EXISTS "Instructors can create offerings" ON public.offerings;
DROP POLICY IF EXISTS "Instructors can update their own offerings" ON public.offerings;
DROP POLICY IF EXISTS "Instructors can delete their own offerings" ON public.offerings;

-- 1. Anyone can view PUBLISHED offerings
CREATE POLICY "Published offerings are viewable by everyone"
  ON public.offerings FOR SELECT
  USING (status = 'published');

-- 2. Instructors can view ALL their own offerings (draft, published, cancelled)
CREATE POLICY "Instructors can view all their offerings"
  ON public.offerings FOR SELECT
  USING (auth.uid() = instructor_id);

-- 3. Authenticated users can create offerings as themselves
CREATE POLICY "Instructors can create offerings"
  ON public.offerings FOR INSERT
  WITH CHECK (auth.uid() = instructor_id);

-- 4. Instructors can update their own offerings
CREATE POLICY "Instructors can update their own offerings"
  ON public.offerings FOR UPDATE
  USING (auth.uid() = instructor_id);

-- 5. Instructors can delete their own offerings
CREATE POLICY "Instructors can delete their own offerings"
  ON public.offerings FOR DELETE
  USING (auth.uid() = instructor_id);

-- ============================================================================
-- STEP 6: Create RLS Policies for RSVPs
-- ============================================================================

-- Drop existing policies if they exist (for clean re-run)
DROP POLICY IF EXISTS "Anyone can create RSVPs" ON public.rsvps;
DROP POLICY IF EXISTS "Users can view their own RSVPs" ON public.rsvps;
DROP POLICY IF EXISTS "Instructors can view RSVPs for their offerings" ON public.rsvps;
DROP POLICY IF EXISTS "Instructors can update RSVPs for their offerings" ON public.rsvps;
DROP POLICY IF EXISTS "Instructors can delete RSVPs for their offerings" ON public.rsvps;

-- 1. Anyone can create an RSVP (public RSVP form)
CREATE POLICY "Anyone can create RSVPs"
  ON public.rsvps FOR INSERT
  WITH CHECK (true);

-- 2. Users can view their own RSVPs (by user_id)
-- NOTE: We removed the auth.users email check because it causes "permission denied" errors
-- The user_id check is sufficient for authenticated users
CREATE POLICY "Users can view their own RSVPs"
  ON public.rsvps FOR SELECT
  USING (
    auth.uid() = user_id
  );

-- 3. Instructors can view all RSVPs for their offerings
CREATE POLICY "Instructors can view RSVPs for their offerings"
  ON public.rsvps FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.offerings
      WHERE offerings.id = rsvps.offering_id
      AND offerings.instructor_id = auth.uid()
    )
  );

-- 4. Instructors can update RSVP status (approve/decline) for their offerings
CREATE POLICY "Instructors can update RSVPs for their offerings"
  ON public.rsvps FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.offerings
      WHERE offerings.id = rsvps.offering_id
      AND offerings.instructor_id = auth.uid()
    )
  );

-- 5. Instructors can delete RSVPs for their offerings
CREATE POLICY "Instructors can delete RSVPs for their offerings"
  ON public.rsvps FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM public.offerings
      WHERE offerings.id = rsvps.offering_id
      AND offerings.instructor_id = auth.uid()
    )
  );

-- ============================================================================
-- STEP 7: Create Helpful Database Views (Optional but Useful)
-- ============================================================================

-- View: Upcoming Published Offerings
CREATE OR REPLACE VIEW public.upcoming_offerings AS
SELECT
  o.*,
  (SELECT COUNT(*) FROM rsvps WHERE rsvps.offering_id = o.id AND rsvps.status = 'approved') as approved_rsvps_count,
  (SELECT COUNT(*) FROM rsvps WHERE rsvps.offering_id = o.id AND rsvps.status = 'pending') as pending_rsvps_count
FROM public.offerings o
WHERE o.status = 'published'
  AND o.date > NOW()
ORDER BY o.date ASC;

-- View: Offerings with RSVP Statistics
CREATE OR REPLACE VIEW public.offerings_with_stats AS
SELECT
  o.*,
  COUNT(CASE WHEN r.status = 'pending' THEN 1 END) as pending_count,
  COUNT(CASE WHEN r.status = 'approved' THEN 1 END) as approved_count,
  COUNT(CASE WHEN r.status = 'declined' THEN 1 END) as declined_count,
  COUNT(r.id) as total_rsvps
FROM public.offerings o
LEFT JOIN public.rsvps r ON r.offering_id = o.id
GROUP BY o.id;

-- Grant SELECT permission on views to authenticated users
GRANT SELECT ON public.upcoming_offerings TO authenticated, anon;
GRANT SELECT ON public.offerings_with_stats TO authenticated;

-- ============================================================================
-- STEP 8: Grant API Access Permissions
-- ============================================================================
-- These grants allow the Supabase REST API (PostgREST) to access the tables
-- Without these, you'll get 404 or 403 errors when querying from your app

-- Grant all permissions to authenticated users (instructors)
GRANT ALL ON public.offerings TO authenticated;
GRANT ALL ON public.rsvps TO authenticated;

-- Grant limited permissions to anonymous users (public access)
GRANT SELECT ON public.offerings TO anon;  -- Anyone can view published offerings (filtered by RLS)
GRANT INSERT ON public.rsvps TO anon;      -- Anyone can submit RSVPs (public RSVP form)

-- Grant usage on sequences (needed for auto-incrementing IDs)
GRANT USAGE, SELECT ON SEQUENCE offerings_id_seq TO authenticated, anon;
GRANT USAGE, SELECT ON SEQUENCE rsvps_id_seq TO authenticated, anon;

-- ============================================================================
-- SETUP COMPLETE!
-- ============================================================================

-- What this script created:
-- ✓ offerings table (stores workshops, events, retreats)
-- ✓ rsvps table (stores registrations)
-- ✓ Performance indexes
-- ✓ Row Level Security (RLS) enabled
-- ✓ Security policies (who can view/create/update/delete)
-- ✓ Helper views for analytics

-- Next Steps:
-- 1. Go to your React app
-- 2. Register a new user at /register
-- 3. Login at /login
-- 4. Go to /dashboard
-- 5. Create your first workshop!

-- Troubleshooting:
-- - If you get "relation already exists" errors, that's OK - it means tables already exist
-- - If policies fail, the DROP POLICY IF EXISTS commands will clean them up
-- - You can re-run this entire script safely
